import { Question } from '../types';

export const QUESTIONS: Question[] = [
  {
    id: 'project-type',
    text: 'What type of digital project are you planning?',
    type: 'select',
    options: ['Website', 'Branding', 'Design System', 'Combined Project'],
    category: 'scope',
    weight: 1.0,
  },
  {
    id: 'target-audience',
    text: 'Who is your primary target audience?',
    type: 'select',
    options: ['B2B Professionals', 'B2C Consumers', 'Internal Team', 'Mixed Audience'],
    category: 'audience',
    weight: 0.8,
  },
  {
    id: 'project-goals',
    text: 'What are your primary goals? (Select all that apply)',
    type: 'multi-select',
    options: [
      'Increase brand awareness',
      'Generate leads',
      'Improve user experience',
      'Launch new product/service',
      'Rebrand existing business',
      'Increase conversions',
    ],
    category: 'goals',
    weight: 0.9,
  },
  {
    id: 'project-scale',
    text: 'How would you describe the scale of this project?',
    type: 'select',
    options: ['Small (1-5 pages/screens)', 'Medium (6-15 pages/screens)', 'Large (16+ pages/screens)', 'Enterprise'],
    category: 'scope',
    weight: 1.2,
  },
  {
    id: 'timeline-preference',
    text: 'What is your ideal timeline?',
    type: 'select',
    options: ['Rush (2-4 weeks)', 'Standard (1-3 months)', 'Flexible (3-6 months)', 'No specific deadline'],
    category: 'constraints',
    weight: 0.7,
  },
  {
    id: 'content-status',
    text: 'Do you have existing content (copy, images, assets)?',
    type: 'select',
    options: ['All content ready', 'Some content ready', 'Need content creation', 'Starting from scratch'],
    category: 'scope',
    weight: 0.6,
  },
  {
    id: 'integration-complexity',
    text: 'What integrations or technical requirements are needed?',
    type: 'multi-select',
    options: [
      'None - standalone project',
      'E-commerce platform',
      'CRM integration',
      'Third-party APIs',
      'Custom backend development',
      'Analytics & tracking',
    ],
    category: 'scope',
    weight: 1.1,
  },
  {
    id: 'brand-maturity',
    text: 'How established is your brand?',
    type: 'select',
    options: ['New brand (starting fresh)', 'Rebranding existing brand', 'Established brand (refinement)', 'Enterprise brand'],
    category: 'audience',
    weight: 0.5,
  },
  {
    id: 'revision-expectations',
    text: 'How many rounds of revisions do you anticipate?',
    type: 'select',
    options: ['1-2 rounds', '3-4 rounds', '5+ rounds', 'Iterative/agile approach'],
    category: 'constraints',
    weight: 0.4,
  },
  {
    id: 'success-metrics',
    text: 'How will you measure success?',
    type: 'select',
    options: [
      'User engagement metrics',
      'Conversion rates',
      'Brand recognition',
      'Time to market',
      'Client satisfaction',
      'Multiple metrics',
    ],
    category: 'goals',
    weight: 0.3,
  },
];
